lidar:
  - driver:
      pcap_play_synchronization: true  # pcap play rate synchronize with the host time
      udp_port: 2368                   #UDP port of lidar
      ptc_port: 9347                   #PTC port of lidar
      device_ip_address: 192.168.123.221 #host_ip_address
      pcap_path: "Your pcap file path" #The path of pcap file
      group_address: 255.255.255.255
      correction_file_path: "Your correction file path" #The path of correction file
      firetimes_path: "Your firetime file path"         #The path of firetimes file
      source_type: 1                   #The type of data source, 1: real-time lidar connection, 2: pcap, 3: packet rosbag    
      frame_start_azimuth: 200         #Frame azimuth for Pandar128, range from 1 to 359, set it less than 0 if you do not want to use it
      standby_mode: -1                 #The standby mode: [-1] is invalit [0] in operation [1] standby
      speed: -1                        #The speed: [-1] invalit, you must make sure your set has been supported by the lidar you are using
      #transform param
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
      #decoder param
      use_timestamp_type: 0           #0 use point cloud timestamp; 1 use receive timestamp
      #fov config, [fov_start, fov_end] range [1, 359], [-1, -1]means use default
      fov_start: -1
      fov_end:  -1
      enable_packet_loss_tool: true     # enable the udp packet loss detection tool
      distance_correction_lidar_type: ""   # Configure the corresponding lidar model when optical centre correction needs to be turned on
      lidar_type: ""                       # When you need to enable XT point cloud S hierarchical correction, configure the corresponding model
      device_udp_src_port: 0               # Filter point clouds for specified source ports in case of multiple lidar, setting >=1024
      device_fault_port: 0                 # Filter fault message for specified source ports in case of multiple lidar, setting >=1024
    ros:
      ros_frame_id: B1_284/lidar_hesai
      ros_recv_packet_topic: hesai_lidar_packets     #Topic used to receive lidar packets from rosbag
      ros_send_packet_topic: hesai_lidar_packets     #Topic used to send lidar raw packets through ROS
      ros_send_point_cloud_topic: lidar/raw          #Topic used to send point cloud through ROS
      send_packet_ros: false                         #true: Send packets through ROS
      send_point_cloud_ros: true                     #true: Send point cloud through ROS    
